---
apiVersion: v1
kind: Secret
metadata:
  name: common-secret
type: Opaque
data:
{{- range $name, $value := .Values.CommonConfig.SecretEnv }}
{{- if not (empty $value) }}
  {{ $name }}: {{ $value | b64enc }}
{{- end }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: common-tls-secret
data:
{{ $root := . }}
{{ range $path, $bytes := .Files.Glob "certs/*" }}
  {{ base $path }}: '{{ $root.Files.Get $path | b64enc }}'
{{ end }}
type: kubernetes.io/tls
---
