{{- if .Values.Gateway.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ $.Release.Name }}
spec:
  selector:
    istio: ingressgateway
  servers:
  {{- range .Values.Gateway.hosts }}        
  - hosts:
    - {{ .host | quote }}
    port:
      name: http
      number: 80
      protocol: HTTP
      {{- end }}
{{- end }}
