---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Release.Name }}
type: Opaque
data:
{{- range $name, $value := .Values.Config.SecretEnv }}
{{- if not (empty $value) }}
  {{ $name }}: {{ $value | b64enc }}
{{- end }}
{{- end }}

